---
- name: Install gnuradio and supporting packages
  hosts: all
  tasks:
  - name: Install python3-pip
    become: yes
    ansible.builtin.apt:
      name: python3-pip
      state: present
  - name: Install build-essential
    become: yes
    ansible.builtin.apt:
      name: build-essential
      state: present
  - name: Install cmake
    become: yes
    ansible.builtin.apt:
      name: cmake
      state: present
  - name: Install gnuradio
    become: yes
    ansible.builtin.apt:
      name: gnuradio
      state: present
  - name: Install gnuradio-dev
    become: yes
    ansible.builtin.apt:
      name: gnuradio-dev
      state: present
  - name: Install vim
    become: yes
    ansible.builtin.apt:
      name: vim
      state: present